name = "miniflare-typescript-esbuild-jest"
type = "javascript"

account_id = ""
workers_dev = true
# route = ""
# zone_id = ""

compatibility_date = "2021-11-15"
compatibility_flags = []

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" },
  { name = "HOLODB_USER", class_name = "HoloDB_User" },
  { name = "HOLODB_POST", class_name = "HoloDB_Post" }
]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
durable_objects_persist = true
